加入校验文件项目
dotnet-campus/dotnetcampus.DotNETBuildSDK pull request #46
Opened 2020-12-04 11:20 UTC by lindexi

2020-12-09 02:56 UTC, walterlv requested changes

2020-12-09 02:56 UTC, walterlv commented on VerifyMd5Task/Program.cs
> +                Environment.Exit(-1);
return -1 不香吗？你又没开其他线程，况且开了让它们强制退出是你预期的吗？？？

2020-12-09 02:56 UTC, walterlv commented on VerifyMd5Task/Program.cs
> +                Environment.Exit(-1);
https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit

2020-12-10 00:38 UTC, lindexi commented on VerifyMd5Task/Program.cs
> +                Environment.Exit(-1);
@walterlv 没错就是这个原因，参阅咱自己内部的 Gitlab 等的占用

2020-12-11 10:37 UTC, walterlv approved these changes

2020-12-11 10:37 UTC, merged